{
    "name": "Intermédiaire de paiement PayFIP",
    "version": "16.0.0.1.1",
    "summary": """Intermédiaire de paiement : Implémentation de PayFIP""",
    "author": "Horanet",
    "website": "https://www.yotech.pro/",
    "license": "AGPL-3",
    "maintainer": "Yotech, Horanet",
    "category": "Accounting",
    "depends": ["payment"],
    "data": [
        "views/payment_views.xml",
        "views/payment_payfip_templates.xml",
        "data/payment_provider.xml",
        "data/draft_payments_recovered_mail.xml",
        "data/cron_check_drafts.xml",
    ],
    "demo": [],
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "application": False,
    "auto_install": False,
    "installable": True,
}
